!classDefinition: #Pepito category: #'Ejercicio 0.1'!
DenotativeObject subclass: #Pepito
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 0.1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Pepito class' category: #'Ejercicio 0.1'!
Pepito class
	instanceVariableNames: ''!

!Pepito class methodsFor: 'as yet unclassified' stamp: 'GS 4/2/2024 00:46:43'!
hola
	^'Chau'! !
